name: 📚 주차별 스터디 주제
description: 이번 주의 스터디 주제를 등록합니다.
title: "[N주차] 주제"
labels: ["주제"]
assignees:
  - j1suk1m
  - cloudmato
  - Hanjise0ng
body:
  - type: input
    id: topic
    attributes:
      label: 📌 주제
      placeholder: 예) 운영체제, 네트워크 등
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## 📢 안내
        - 주차별 스터디 주제를 등록하기 위한 이슈입니다.  
        - 모든 팀원은 이 이슈에 자동으로 할당됩니다.
        - 각 팀원은 하위 이슈로 질문을 등록해주세요.